from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from fastapi.testclient import TestClient

from apps.ares.ares.profiles import ClientProfile, write_client_profile
from plugins.ares.dashboard.plugin_api import router


def _client() -> TestClient:
    app = FastAPI()
    app.include_router(router)
    return TestClient(app)


def test_ares_dashboard_overview_guides_when_no_clients(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))

    response = _client().get("/overview")

    assert response.status_code == 200
    payload = response.json()
    assert payload["selected_client"] is None
    assert "ares setup --client demo-wholesaler" in payload["setup_command"]
    assert payload["operator_view"]["today_summary"]["status"] == "needs_input"
    assert payload["operator_view"]["readiness_cards"][0]["id"] == "local_boundary"
    assert payload["audit"]["local_only"] is True


def test_ares_dashboard_overview_returns_command_center(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    response = _client().get("/overview?client=demo")

    assert response.status_code == 200
    payload = response.json()
    assert payload["selected_client"]["client_slug"] == "demo"
    assert payload["metrics"]["pending_approvals"] == 0
    assert payload["paths"]["exports"].endswith("/clients/demo/exports")
    assert payload["data_inventory"]["has_business_data"] is False
    assert payload["data_inventory"]["has_input_files"] is False
    assert payload["work_queue"][0]["title"] == "Load real business files"
    assert payload["work_queue"][0]["action"] is None
    assert payload["work_queue"][1]["action"] == "validate-inputs"
    assert payload["operator_surface"]["access_model"] == "dashboard_first"
    assert payload["operator_surface"]["operator_home"] == "/ares"
    assert payload["operator_surface"]["cli_role"] == "admin_dev_fallback"
    assert payload["operator_surface"]["local_only"] is True
    assert payload["operator_surface"]["approval_first"] is True
    assert payload["operator_surface"]["live_external_api_called"] is False
    assert payload["operator_surface"]["has_loaded_input"] is False
    assert "today" in payload["operator_surface"]["primary_action_ids"]
    assert any(action["action"] == "validate-inputs" for action in payload["operator_surface"]["actions"])
    assert payload["operator_view"]["today_summary"]["headline"] == "Load real business files"
    assert payload["operator_view"]["today_summary"]["next_action"]["action"] == "validate-inputs"
    assert payload["operator_view"]["business_cards"][0]["label"] == "Money to collect"
    assert payload["operator_view"]["business_cards"][0]["action"] == "payment-radar"
    assert any(card["id"] == "local_boundary" and card["status"] == "ready" for card in payload["operator_view"]["readiness_cards"])
    assert payload["operator_view"]["empty_states"]["reports"]
    commands = [
        command
        for group in payload["command_groups"]
        for command in group["commands"]
    ]
    assert any(command["id"] == "today" and command["action"] == "today" for command in commands)
    payment_radar = next(command for command in commands if command["id"] == "payment_radar")
    assert payment_radar["requires_data"] is True
    assert payment_radar["available"] is False
    assert payment_radar["state"] == "needs_data"
    assert payload["audit"]["live_external_api_called"] is False


def test_ares_dashboard_operator_view_summarizes_reports(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))
    reports_dir = tmp_path / ".ares" / "clients" / "demo" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    report = reports_dir / "20260523T010203Z-payment-radar.md"
    report.write_text("# Payment radar\n\nCollections reviewed.", encoding="utf-8")

    response = _client().get("/overview?client=demo")

    assert response.status_code == 200
    payload = response.json()
    proof = payload["operator_view"]["proof_items"][0]
    assert proof["title"] == "Payment Radar"
    assert proof["status"] == "created"
    assert proof["path"].endswith("20260523T010203Z-payment-radar.md")
    assert proof["summary"] == "Local proof report generated by Ares."


def test_ares_dashboard_run_validate_inputs_action(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    response = _client().post("/run", json={"client": "demo", "action": "validate-inputs"})

    assert response.status_code == 200
    payload = response.json()
    assert payload["client_id"] == "demo"
    assert payload["action"] == "validate-inputs"
    assert "Input check" in payload["message"]
    assert payload["payload"]["client_id"] == "demo"
    assert Path(payload["report"]["markdown_path"]).exists()
    assert Path(payload["report"]["json_path"]).exists()
    assert payload["audit"]["approval_first"] is True


def test_ares_dashboard_rejects_unknown_action(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    response = _client().post("/run", json={"client": "demo", "action": "wire-money"})

    assert response.status_code == 400
    assert "Unsupported Ares dashboard action" in response.text


def test_ares_dashboard_get_report(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    # Create dummy reports folder and a dummy markdown report
    reports_dir = tmp_path / ".ares" / "clients" / "demo" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    dummy_report = reports_dir / "daily_audit.md"
    dummy_report.write_text("# Daily Audit Report\n\nAll systems nominal.", encoding="utf-8")

    # Happy path
    response = _client().get(f"/report?client=demo&path={dummy_report.absolute()}")
    assert response.status_code == 200
    payload = response.json()
    assert payload["name"] == "daily_audit.md"
    assert "Daily Audit Report" in payload["content"]

    # Traversal attempt outside client reports directory
    outside_file = tmp_path / "outside.md"
    outside_file.write_text("secrets", encoding="utf-8")
    response_traversal = _client().get(f"/report?client=demo&path={outside_file.absolute()}")
    assert response_traversal.status_code == 400
    assert "Invalid report path" in response_traversal.json()["detail"]


def test_ares_dashboard_websocket(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    client = _client()
    with client.websocket_connect("/ws") as websocket:
        # Just establish the connection and verify websocket connection works
        assert websocket is not None


def test_ares_dashboard_run_action_with_missing_params(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setenv("ARES_HOME", str(tmp_path / ".ares"))
    write_client_profile(ClientProfile(client_slug="demo", business_name="Demo Wholesale", owner_name="Owner"))

    # Running mobile-reply without the reply parameter should return 400
    response = _client().post("/run", json={"client": "demo", "action": "mobile-reply"})
    assert response.status_code == 400
    assert "Missing 'reply' parameter" in response.json()["detail"]
