"""Ares wholesaler command-center command library."""

from __future__ import annotations

from typing import Any


def build_wholesaler_command_library(client_slug: str) -> list[dict[str, Any]]:
    """Return daily-use Ares commands grouped by wholesaler operating job."""
    client = client_slug
    return [
        {
            "id": "today",
            "section": "Today",
            "label": "Today Command Center",
            "cadence": "Every morning",
            "intent": "Ingest new files, build the daily brief, and show owner approvals.",
            "command": f"ares today --client {client}",
            "action": "today",
            "primary": True,
            "requires_data": False,
        },
        {
            "id": "validate_inputs",
            "section": "Today",
            "label": "Check Dropped Files",
            "cadence": "Before every run",
            "intent": "Check whether Tally/Busy exports and inbox text files are parseable.",
            "command": f"ares validate-inputs --client {client}",
            "action": "validate-inputs",
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "morning_run",
            "section": "Today",
            "label": "Morning Run",
            "cadence": "Every morning",
            "intent": "Run ingestion, payment radar, daily brief, and owner approval summary.",
            "command": f"ares morning-run --client {client}",
            "action": "morning-run",
            "primary": True,
            "requires_data": False,
        },
        {
            "id": "daily_brief",
            "section": "Today",
            "label": "Daily Brief",
            "cadence": "Every morning",
            "intent": "Read today's payments, stock, orders, and top actions without creating new approvals.",
            "command": f"ares run-workflow --client {client} --workflow daily-brief",
            "action": "daily-brief",
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "mobile_approvals",
            "section": "Owner Approvals",
            "label": "Owner Approval Prompt",
            "cadence": "After draft actions",
            "intent": "Show WhatsApp/Telegram-friendly approval text for the owner.",
            "command": f"ares mobile-approvals --client {client}",
            "action": "mobile-approvals",
            "primary": True,
            "requires_data": False,
        },
        {
            "id": "approval_center",
            "section": "Owner Approvals",
            "label": "Approval Center",
            "cadence": "Any time",
            "intent": "Review pending approval requests before any ledger-impacting action.",
            "command": f"ares approval-center --client {client}",
            "action": "approval-center",
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "mobile_reply",
            "section": "Owner Approvals",
            "label": "Process Owner Reply",
            "cadence": "When owner replies",
            "intent": "Execute an approved action or record a rejection/edit.",
            "command": f"ares mobile-reply --client {client} --reply \"haan appr_xxx\"",
            "action": "mobile-reply",
            "primary": False,
            "requires_data": True,
        },
        {
            "id": "payment_radar",
            "section": "Collections",
            "label": "Payment Radar",
            "cadence": "Daily and evening",
            "intent": "Find overdue invoices and draft collection follow-ups for approval.",
            "command": f"ares run-workflow --client {client} --workflow payment-radar",
            "action": "payment-radar",
            "primary": True,
            "requires_data": True,
        },
        {
            "id": "stock_radar",
            "section": "Inventory",
            "label": "Stock Radar",
            "cadence": "Daily before dispatch",
            "intent": "Find low-stock SKUs and reorder suggestions from local stock exports.",
            "command": f"ares run-workflow --client {client} --workflow stock-radar",
            "action": "stock-radar",
            "primary": True,
            "requires_data": True,
        },
        {
            "id": "order_capture",
            "section": "Orders",
            "label": "Pending Orders",
            "cadence": "After inbox drops",
            "intent": "Review captured customer orders and pending dispatch decisions.",
            "command": f"ares run-workflow --client {client} --workflow order-capture",
            "action": "order-capture",
            "primary": False,
            "requires_data": True,
        },
        {
            "id": "weekly_war_room",
            "section": "Weekly Review",
            "label": "Weekly War Room",
            "cadence": "Weekly",
            "intent": "Review the week across payments, stock, orders, and operating risks.",
            "command": f"ares run-workflow --client {client} --workflow weekly-war-room",
            "action": "weekly-war-room",
            "primary": False,
            "requires_data": True,
        },
        {
            "id": "gstr1",
            "section": "GST",
            "label": "GSTR-1 Draft",
            "cadence": "Monthly",
            "intent": "Prepare a local approval-gated GSTR-1 draft from available invoice data.",
            "command": f"ares prepare-gstr1 --client {client} --period YYYY-MM --seller-gstin GSTIN",
            "action": "prepare-gstr1",
            "primary": False,
            "requires_data": True,
        },
        {
            "id": "autonomous_cycle",
            "section": "Operator",
            "label": "Autonomous Cycle",
            "cadence": "Manual operator check",
            "intent": "Run eyes, memory, payment radar, and owner-facing draft action summary.",
            "command": f"ares autonomous-cycle --client {client}",
            "action": "autonomous-cycle",
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "operator_shell",
            "section": "Operator",
            "label": "Operator Shell",
            "cadence": "Any time",
            "intent": "Show local metrics, sections, readiness, and next actions for the wholesaler workspace.",
            "command": f"ares operator-shell --client {client}",
            "action": "operator-shell",
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "classic_chat",
            "section": "Agent Interfaces",
            "label": "Classic Chat",
            "cadence": "As needed",
            "intent": "Open classic Ares chat inside the generated Ares client context.",
            "command": f"ares chat --client {client}",
            "action": None,
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "terminal_tui",
            "section": "Agent Interfaces",
            "label": "Terminal TUI",
            "cadence": "As needed",
            "intent": "Open the Ares terminal UI as the Ares wholesaler agent.",
            "command": f"ares tui --client {client}",
            "action": None,
            "primary": False,
            "requires_data": False,
        },
        {
            "id": "web_dashboard",
            "section": "Agent Interfaces",
            "label": "Web Dashboard",
            "cadence": "As needed",
            "intent": "Open the Ares web command center and embedded Ares TUI.",
            "command": f"ares dashboard --client {client} --port 9119",
            "action": None,
            "primary": False,
            "requires_data": False,
        },
    ]


def group_commands(commands: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for command in commands:
        groups.setdefault(str(command["section"]), []).append(command)
    return [{"section": section, "commands": items} for section, items in groups.items()]
